#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config leaf_monocle true
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config click_to_focus true

# Border colors
bspc config focused_border_color "#CCCFED"
bspc config active_border_color "#D7DBF7"
bspc config normal_border_color "#D7DBF7"
bspc config presel_feedback_color "#0077FF"

bspc monitor -d 0

# Set non-bspwm settings
xrdb ~/.Xresources
xmodmap ~/.Xmodmap
xsetroot -cursor_name left_ptr& # Set the default cursor to pointer instead of X
xsetroot -solid '#E6EAFF'
#feh --bg-fill ~/Photos/Ditch\ Day\ 1/kimono.jpg
xinput disable "SynPS/2 Synaptics TouchPad"
xbindkeys
pactl load-module module-equalizer-sink
pactl load-module module-dbus-protocol

# Terminate running polybar instances
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Start dependencies
exec polybar laptop &
sxhkd &
exec /home/a3a/bin/dynamic_bspwm.sh
