#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config leaf_monocle true
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config remove_disabled_monitor true

# Border colors
bspc config focused_border_color "#34495E"
bspc config active_border_color "#34495E"
bspc config normal_border_color "#2C3E50"
bspc config presel_feedback_color "#2ECC71"
bspc config urgent_border_color "#E74C3C"
bspc config focused_locked_border_color "#2ECC71"
bspc config active_locked_border_color "#2ECC71"
bspc config normal_locked_border_color "#2C3E50"
bspc config focused_sticky_border_color "#9B59B6"
bspc config active_sticky_border_color "#9B59B6"
bspc config normal_sticky_border_color "#2C3E50"
bspc config focused_private_border_color "#3498DB"
bspc config active_private_border_color "#3498DB"
bspc config normal_private_border_color "#2C3E50"

# Padding for lemonbar
bspc config top_padding 32

bspc monitor -d I

# Set non-bspwm settings
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr& # Set the default cursor to pointer instead of X
hsetroot -solid '#2C3E50'

# Start dependencies
#compton -b --sw-opti &
exec /home/tyler/bin/runbar.sh &
sxhkd -c /home/tyler/.config/sxhkd/sxhkdrc.bswpm &
exec /home/tyler/bin/dynamic_bspwm.sh
